### ISSUE TITLE
Check whether rustc eliminates arithmetic from const zero values

### ISSUE THREAD

**Issue by unzvfu** [mir-protocol/plonky#75]
In a [comment](https://github.com/mir-protocol/plonky/issues/68#issuecomment-671125810) on #68, it was noted that the value of the constant `ORDER[2]` for the Tweedle* curves is zero, and so the compiler _should_ simplify/eliminate arithmetic involving that value. This should be verified over at https://godbolt.org.

**Comment by MrNeither** [comment]
* Compiler version - 1.48.0 (same results were using nightly version);
* Optimization level - 3 (same as in project, in cargo.toml);
* Examples 1,2 - if we don't use cycle, we achieve an optimization, function immediately return either 0 or desired value;
* Example 3. - a small optimization is achieved because of large number of constants.
* Example 4 - better optimization because of lack of cycle.

![image](https://user-images.githubusercontent.com/42472993/102125714-c4819880-3e52-11eb-8048-0c76a2c385ad.png)
![image](https://user-images.githubusercontent.com/42472993/102125726-c9dee300-3e52-11eb-8f5b-bf26e3c28365.png)

**Comment by unzvfu** [comment]
Thanks @MrNeither! I agree that this evidence is convincing. I have also verified that the appropriate assembly is generated when `ORDER` is accessed in a loop with index `j%4` where the loop is an explicit `for` loop with upper bound a const generic parameter. I think that scenario should be the most difficult one we'll throw at the compiler, so I'm satisfied this issue can be closed.

On a related note, with the Tweedle curves the top word of `ORDER` is equal to `0x4000000000000000`; I have also verified that the compiler emits the appropriate shift instead of a multiplication in that case.
